src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    const SECTIONS = ['Critiques','Découvertes','Bizarreries'];
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre_article;

    /**
     * @ORM\Column(type="text")
     */
    private $texte_article;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image_article;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Choice(choices=Article::SECTIONS, message="Le nom de section choisi est invalide")
     */
    private $section;

    /**
     * @ORM\OneToMany(targetEntity=Commentaires::class, mappedBy="id_article")
     */
    private $commentaires;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $textePresentation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sousTitreArticle;

    /**
     * @ORM\OneToOne(targetEntity=Roman::class, mappedBy="idArticle", cascade={"persist", "remove"})
     */
    private $romanId;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitreArticle(): ?string
    {
        return $this->titre_article;
    }

    public function setTitreArticle(string $titre_article): self
    {
        $this->titre_article = $titre_article;

        return $this;
    }

    public function getTexteArticle(): ?string
    {
        return $this->texte_article;
    }

    public function setTexteArticle(string $texte_article): self
    {
        $this->texte_article = $texte_article;

        return $this;
    }

    public function getImageArticle(): ?string
    {
        return $this->image_article;
    }

    public function setImageArticle(string $image_article): self
    {
        $this->image_article = $image_article;

        return $this;
    }

    public function getSection(): ?string
    {
        return $this->section;
    }

    public function setSection(string $section): self
    {
        $this->section = $section;

        return $this;
    }

    /**
     * @return Collection|Commentaires[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaires $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setIdArticle($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaires $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getIdArticle() === $this) {
                $commentaire->setIdArticle(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getTextePresentation(): ?string
    {
        return $this->textePresentation;
    }

    public function setTextePresentation(string $textePresentation): self
    {
        $this->textePresentation = $textePresentation;

        return $this;
    }

    public function getSousTitreArticle(): ?string
    {
        return $this->sousTitreArticle;
    }

    public function setSousTitreArticle(string $sousTitreArticle): self
    {
        $this->sousTitreArticle = $sousTitreArticle;

        return $this;
    }

    public function getRomanId(): ?Roman
    {
        return $this->romanId;
    }

    public function setRomanId(Roman $romanId): self
    {
        $this->romanId = $romanId;

        // set the owning side of the relation if necessary
        if ($romanId->getIdArticle() !== $this) {
            $romanId->setIdArticle($this);
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(
 *     fields={"email"},
 *     message="L'email indiqué est déjà utilisé"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     * @Assert\Count(
     *     max = 1,
     *     maxMessage = "You cannot specify more than {{ limit }} role"
     * )
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\Length(min="5", minMessage="votre mot de passe doit faire au moins 5 caractères")
     */
    private $password;

    private $plainPassword;

    /**
     * @ORM\OneToMany(targetEntity=Commentaires::class, mappedBy="userId")
     */
    private $commentairesId;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $profileImage;

    /**
     * @ORM\Column(type="boolean")
     */
    private $locked;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    public function __construct()
    {
        $this->commentairesId = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    /**
     * @param mixed $plainPassword
     */
    public function setPlainPassword($plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        $this->plainPassword = null;
    }

    /**
     * @return Collection|Commentaires[]
     */
    public function getCommentairesId(): Collection
    {
        return $this->commentairesId;
    }

    public function addCommentairesId(Commentaires $commentairesId): self
    {
        if (!$this->commentairesId->contains($commentairesId)) {
            $this->commentairesId[] = $commentairesId;
            $commentairesId->setUserId($this);
        }

        return $this;
    }

    public function removeCommentairesId(Commentaires $commentairesId): self
    {
        if ($this->commentairesId->removeElement($commentairesId)) {
            // set the owning side to null (unless already changed)
            if ($commentairesId->getUserId() === $this) {
                $commentairesId->setUserId(null);
            }
        }

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getProfileImage(): ?string
    {
        return $this->profileImage;
    }

    public function setProfileImage(string $profileImage): self
    {
        $this->profileImage = $profileImage;

        return $this;
    }

    public function getLocked(): ?bool
    {
        return $this->locked;
    }

    public function setLocked(bool $locked): self
    {
        $this->locked = $locked;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }
}

templates/pages/activateAccount.html.twig
    <section class="single-blog-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="border-top">
                        <div class="blog-area">

                            <h1>Bienvenue {{ user.email }}!</h1>

                            <p>Veuillez activer votre compte en suivant <a href="{{ url('activateAccount',{'id': user.id}) }}">ce lien</a>.</p>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

templates/pages/adminModifUser.html.twig
{% extends 'general.html.twig' %}

{% block content %}
    <section class="single-blog-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="border-top">
                        <div class="blog-area">

                            <h2 class="inscriptionTitle">
                                {% if app.request.attributes.get('_route') == 'updateUserAdmin' %}
                                Modifier utilisateur
                                {% elseif app.request.attributes.get('_route') == 'userCreationPage' %}
                                    Création utilisateur
                                {% endif %}
                            </h2>

                            {{ form_start(userForm) }}
                            {{ form_row(userForm.email) }}
                            {{ form_row(userForm.roles) }}
                            {{ form_row(userForm.name) }}
                            {{ form_row(userForm.password) }}
                            {{ form_row(userForm.profileImage) }}
                            {{ form_row(userForm.locked) }}
                            {{ form_row(userForm.active) }}
                            <div class="inscriptionButton">
                                <input type="submit" id="inscrBut" value="Valider">
                            </div>

                            {{ form_end(userForm) }}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/pages/changerProfil.html.twig
{% extends 'general.html.twig' %}

{% block content %}
<section class="single-blog-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="border-top">
                    <div class="blog-area">

                        <h2 class="inscriptionTitle">Changer profil</h2>

                        {{ form_start(userForm) }}
                        {{ form_row(userForm.email) }}
                        {{ form_row(userForm.name) }}
                        {{ form_row(userForm.profileImage) }}
                        <div class="inscriptionButton">
                            <input type="submit" id="inscrBut" value="Valider">
                        </div>

                        {{ form_end(userForm) }}

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/pages/connection.html.twig
{% extends 'general.html.twig' %}

{% block content %}
    <section class="single-blog-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="border-top">
                        <div class="blog-area">

                            {% if app.user %}
                                <div class="col-md-2"><p></p></div>
                                <div class="col-md-8">
                                    <p>Vous êtes connecté en tant que {{ app.user.username }}, <a href="{{ path('app_logout') }}">se déconnecter</a></p>
                                </div>
                                <div class="col-md-2"><p></p></div>
                            {% else %}
                                <h2 class="connexionTitle">Connexion</h2>
                                {% if error %}
                                    <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                                {% endif %}

                                <form action="{{ path('connectionPage') }}" method="post">
                                    <div class="connexionForm">
                                        <input type="email" required name="_username" id="email" placeholder="Adresse mail">
                                    </div>
                                    <div class="connexionForm">
                                        <input type="password" required name="_password" id="password" placeholder="Password">
                                    </div>
                                    <div class="connexionButton">
                                        <input type="submit" id="connexBut" value="Connexion">
                                    </div>
                                    <div class="connexionForm">
                                        <p><a href="{{ path('app_forgot_password_request') }}">Mot de passe oublié ?</a></p>
                                    </div>

                                </form>

                            {% endif %}



                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/pages/contact.html.twig
{% extends 'general.html.twig' %}

{% block content %}
    <section class="single-blog-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="border-top">
                        <div class="col-md-2"><p></p></div>
                        <div class="col-md-8">
                            <div class="blog-area">
                                <div class="blog-area-part">

                                    <h2>Contact</h2>
                                    <p> Vous voulez me laisser un message directement ? Vous pouvez me contacter via ce formulaire !</p>

                                    <div class="for-style">
                                        {{ form_start(contactForm) }}
                                        {{ form_row(contactForm.emailContact, {'label':'Votre email :'}) }}
                                        {{ form_row(contactForm.nameContact, {'label':'Votre nom :'}) }}
                                        {{ form_row(contactForm.textContact, {'label':'Votre message :'}) }}
                                        <div class="connexionButton">
                                            <input type="submit" id="connexBut" value="Valider">
                                        </div>
                                        {{ form_end(contactForm) }}

                                    </div>

                                </div>


                            </div>
                        </div>
                        <div class="col-md-2"><p></p></div>

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/pages/creationArticle.html.twig
{% extends 'general.html.twig' %}

{% block content %}
    <section class="single-blog-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="border-top">

                        <div class="blog-area">
                            <div class="blog-area-part">
                                <h2>{% if editMode %}
                                    Modifier l'Article
                                    {% else %}
                                    Créer un nouvel article
                                    {% endif %}
                                </h2>

                                {{ form_start(articleForm) }}
                                <h3>Données Article :</h3>

                                {{ form_row(articleForm.titre_article, {'label': 'Titre de l\'article :' }) }}
                                {{ form_row(articleForm.section, {'label': 'Choisir la section de l\'article :'}) }}
                                {{ form_row(articleForm.textePresentation, {'label': 'Texte de présentation de l\'article :'}) }}
                                {{ form_row(articleForm.sousTitreArticle, {'label': 'Sous-titre de l\'article :'}) }}
                                {{ form_row(articleForm.image_article, {'label': 'Choisir une image :'}) }}
                                {{ form_row(articleForm.texte_article, {'label': 'Ecrire le texte de l\'article :'}) }}

                                <h3>Données Roman :</h3>
                                {{ form_row(articleForm.romanId.titreRoman, {'label': 'Le titre du roman : :'}) }}
                                {{ form_row(articleForm.romanId.auteur, {'label': 'L\'auteur du roman :'}) }}
                                {{ form_row(articleForm.romanId.genres, {'label': 'Le/les genre(s) du roman :'}) }}
                                {{ form_row(articleForm.romanId.maisonEdition, {'label': 'La maison d\'édition du roman :'}) }}
                                {{ form_row(articleForm.romanId.editionYear, {'label': 'L\'année d\'édition du roman :'}) }}
                                {{ form_row(articleForm.romanId.note, {'label': 'La note du roman :'}) }}

                                <br>
                                <div>
                                    <input type="submit" value="{% if editMode %}
                                    Enregistrer les modifications
                                    {% else %}
                                    Enregistrer l'article
                                    {% endif %}">
                                </div>

                                {{ form_end(articleForm) }}

                              {#
                                {{ form_start(romanForm) }}

                                <label for="">Titre du roman :</label>
                                {{ form_widget(romanForm.titreRoman) }}
                                <label for="">Nom de l'auteur :</label>
                                {{ form_widget(romanForm.auteur) }}
                                <label for="">Genre(s) du roman :</label>
                                {{ form_widget(romanForm.genres) }}
                                <label for="">Maison d'édition du roman :</label>
                                {{ form_widget(romanForm.maisonEdition) }}
                                <label for="">Année d'édition du roman :</label>
                                {{ form_widget(romanForm.editionYear) }}
                                <label for="">Donner une note :</label>
                                {{ form_widget(romanForm.note) }}


                                {{ form_end(romanForm) }} #}



                            </div>

                        </div>


                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/pages/editComment.html.twig
{% extends 'general.html.twig' %}

{% block content %}
    <section class="single-blog-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="border-top">
                        <div class="blog-area">

                            <h2 class="connexionTitle">Modifier commentaire</h2>

                            {{ form_start(commentsForm) }}

                            {{ form_row(commentsForm.texte_commentaire, {'label':'Modifier votre commentaire :'}) }}
                            <div class="commentPost">
                                <input type="submit" value="Envoyer">
                            </div>
                            {{ form_end(commentsForm) }}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/pages/index.html.twig
{% extends 'general.html.twig' %}

{% block content %}
    <section class="bg-text-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="bg-text">
                        <h3>Le blog de Thibault</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                            et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                            ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="blog-post-area">
        <div class="container">
            <div class="border-top">
                <div class="blog-post-area-style">

                    <div class="row">
                        {% for lastArticles in articlesPage.items %}
                        <div class="col-md-4">
                            <div class="single-post">
                                <a href="{{ path('articlePage', {'id': lastArticles.id}) }}">
                                    <img class="smallImages" src="{{ asset('img/' ~ lastArticles.imageArticle) }}" alt="">
                                </a>
                                <h3>
                                    <a href="{{ path('articlePage', {'id': lastArticles.id}) }}">{{lastArticles.titreArticle}}</a>
                                </h3>
                                <p>{{ lastArticles.textePresentation }}</p>
                                <h4><span>Créé le {{ lastArticles.createdAt | date("d/m/Y") }}</span></h4>
                            </div>
                        </div>
                        {% endfor %}


                    </div>




                </div>
            </div>
        </div>
        <div class="pegination">
            <!--
            <ul>
                <li><i class="fa fa-angle-left" aria-hidden="true"></i></li>
                <li class="active">1</li>
                <li>2</li>
                <li>3</li>
                <li><i class="fa fa-angle-right" aria-hidden="true"></i></li>
            </ul>
-->

            <div class="nav-links">
                {% for i in 1..(articlesPage.totalItemCount/articlesPage.itemNumberPerPage + 1) | round(0, 'floor') %}
                    <a class="page-numbers {{   i == app.request.get('page') ? 'current' : '' }}"
                       href="{{ url(app.request.get('_route'), app.request.query.all() | merge({page: i}) ) }}">{{ i }}</a>
                {% endfor %}

                {# <a class="page-numbers" href="{{ url(app.request.get('_route'), {'name': app.request.get('name'), 'page': (i+1)}) }}"><i class="fa fa-angle-right" aria-hidden="true"></i></a> #}
            </div>
        </div>

    </section>
{% endblock %}

templates/pages/inscription.html.twig
{% extends 'general.html.twig' %}

{% block content %}
    <section class="single-blog-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="border-top">
                        <div class="blog-area">

                            <h2 class="inscriptionTitle">Inscription</h2>

                            {{ form_start(userForm) }}
                            {{ form_row(userForm.email) }}
                            {{ form_row(userForm.name) }}
                            {{ form_row(userForm.password) }}
                            <div class="inscriptionButton">
                                <input type="submit" id="inscrBut" value="Valider">
                            </div>

                            {{ form_end(userForm) }}


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/pages/resultatsRecherche.html.twig
{% extends 'general.html.twig' %}

{% block content %}
    <section class="blog-post-area">
        <div class="container">
            <div class="border-top">
                <div class="blog-post-area-style">

                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-6">
                            <h2>Votre recherche :</h2>
                            {{ form_start(searchForm) }}
                            {{ form_row(searchForm.titre_article, {'label': " ", 'attr': {'placeholder': 'Nom de l\'article recherché...'}}) }}
                            {{ form_row(searchForm.section, {'label': " "}) }}
                            <button class="btn-primary" type="submit"><i class="fas fa-search"></i></button>
                            {{ form_end(searchForm) }}
                        </div>

                        <div class="col-md-3"></div>
                    </div>

                    <div class="row">
                        <div class="col-md-4"></div>
                        <div class="col-md-4">
                            <h2> Résultat(s) de la recherche :</h2>
                        </div>
                        <div class="col-md-4"></div>
                    </div>


                    <div class="row">
                        {% for articlesResults in articlesSearch.items %}
                            <div class="col-md-4">
                                <div class="single-post">
                                    <a href="{{ path('articlePage', {'id': articlesResults.id}) }}"><img class="smallImages" src="{{ asset('img/' ~ articlesResults.imageArticle) }}" alt=""></a>
                                    <h3><a href="{{ path('articlePage', {'id': articlesResults.id}) }}">{{articlesResults.titreArticle}}</a></h3>
                                    <p>{{ articlesResults.textePresentation }}</p>
                                    <h4><span>Créé le {{ articlesResults.createdAt | date("d/m/Y") }}</span></h4>
                                </div>
                            </div>
                        {% endfor %}
                    </div>



                </div>
            </div>
        </div>
        <div class="pegination">


            <div class="nav-links">
                {% for i in 1..(articlesSearch.totalItemCount/articlesSearch.itemNumberPerPage + 1) | round(0, 'floor') %}
                    <a class="page-numbers {{   i == app.request.get('page') ? 'current' : '' }}"
                       href="{{ url(app.request.get('_route'), app.request.query.all() | merge({page: i}) ) }}">{{ i }}</a>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

templates/pages/section.html.twig
{% extends 'general.html.twig' %}

{% block content %}
    <section class="blog-post-area">
        <div class="container">
            <div class="border-top">
                <div class="blog-post-area-style">

                    <div class="row">

                        {% for sectionType in sectionPages.items %}
                        <div class="col-md-4">
                            <div class="single-post">
                                <a href="{{ path('articlePage', {id: sectionType.id}) }}">
                                    <img class="smallImages" src="{{ asset('img/' ~ sectionType.imageArticle) }}" alt="">
                                </a>
                                <h3>
                                    <a href="{{ path('articlePage', {id: sectionType.id}) }}">{{sectionType.titreArticle}}</a>
                                </h3>
                                <p>{{ sectionType.textePresentation }}</p>
                                <h4><span>Créé le {{ sectionType.createdAt | date("d/m/Y") }}</span></h4>
                            </div>
                        </div>
                        {% endfor %}

                    </div>

                    {% if is_granted('ROLE_ADMIN') %}
                    <div class="single-blog-area">
                        <div class="col-md-4">
                            <form action="{{ path('articleCreationPage') }}" method="post">
                                <div class="creationButton">
                                    <input type="submit" id="createArt" value="Créer un article">
                                </div>
                            </form>
                        </div>
                        <div class="col-md-8"><p> </p></div>
                    </div>
                    {% endif %}

                </div>
            </div>
        </div>
        <div class="pegination">


            <div class="nav-links">

                {% for i in 1..(sectionPages.totalItemCount/sectionPages.itemNumberPerPage + 1) | round(0, 'floor') %}
                    <a class="page-numbers {{   i == app.request.get('page') ? 'current' : '' }}"
                       href="{{ url(app.request.get('_route'), {'sectionName': app.request.get('sectionName'), 'page':i}  ) }}">{{ i }}</a>
                {% endfor %}

                {# {% for i in 1..(sectionPages.totalItemCount/result.results.itemNumberPerPage + 1) | round(0, 'floor')  %}
                    <a href="{{  url(app.request.get('_route'), app.request.query.all() | merge({page: i}) ) }}"
                       class="page-link btn btn-sm btn-primary {{  i == app.request.get('page') ? 'current' : ''  }}">{{ i }}</a>
                {% endfor %} #}



            </div>
        </div>
    </section>

{% endblock %}